import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RobotoMono = Roboto_Mono({
    weight: "400",
    style: "normal"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"h-screen " + RobotoMono.className}
      >
        {children}
      </body>
    </html>
  );
}
